// Generated by SSC Studio. Edit .ssc-studio/content.json through Studio.
package net.onixary.shapeShifterCurseFabric.studio;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.onixary.shapeShifterCurseFabric.perk.NormalPerk;
import net.onixary.shapeShifterCurseFabric.perk.PerkTree;
import net.onixary.shapeShifterCurseFabric.perk.RegPerks;
import net.onixary.shapeShifterCurseFabric.util.util.cost.BaseCost;
import net.onixary.shapeShifterCurseFabric.util.util.cost.RegCostType;

public final class StudioGenerated {
  public static void register() {
    RegPerks.registerPerkCommon(new NormalPerk(Identifier.parse("shape-shifter-curse:snowfox_root")).setName(Component.literal("snowfox_root")).setDesc(Component.literal("")).setIcon(Identifier.parse("shape-shifter-curse:textures/perk/fallback.png")).cost(new BaseCost(RegCostType.COST_XP, 0)).addPower().removePower());
    PerkTree tree0 = new PerkTree(Identifier.parse("shape-shifter-curse:f_snowfox_tree"));
    tree0.addNode(Identifier.parse("shape-shifter-curse:snowfox_root"), 0, 0);
    RegPerks.registerPerkTree(tree0);
  }
}
