# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
loader_version=0.19.3
# Mod Properties
mod_version=1.10.0
maven_group=net.wuhenqiubai
build_type=dev
build_number=22
archives_base_name=shape-shifter-curse-fabric
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.6+1.21.11
apoli_version=2.12.10
calio_version=1.11.2
mod_menu_version=17.0.0
cca_version=7.3.2
clothconfig_version=21.11.153
pehkui_version=3.8.5+1.21.11
pal_version=1.1.9+mc.1.21.11
geckolib_version=5.4.5
trinkets_version=3.11.0-beta.2+1.21.11
#satin_version=2.0.0