# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5

# Mod Properties
mod_version=1.10.0.28
maven_group=net.wuhenqiubai
archives_base_name=shape-shifter-curse-unofficial

# Dependencies
fabric_version=0.155.3+26.1.2
apoli_version=2.12.13+26.1.2
calio_version=1.11.4
mod_menu_version=18.0.1
cca_version=8.0.1
clothconfig_version=26.1.154
pehkui_version=3.8.5+26.1.2
pal_version=1.2.6+mc.26.1
geckolib_version=5.5.1
trinkets_version=4.0.0+26.1
jei_version = 29.37.0.98

special_build_version =