pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Fabric-BMCL'
            url = 'https://bmclapi2.bangbang93.com/maven/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
